name: application_musicale
description: Application musicale

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dio: ^4.0.0
  http:
  json_annotation: ^4.0.1
  flutter_svg: ^1.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
  - asset/image/
  - asset/icones/
  fonts:
    - family:  AppIcons
      fonts:
        - asset: asset/font/AppIcons.ttf
    - family: SF-Pro-Display
      fonts:
        - asset: asset/font/SF-Pro-Display-Bold.otf
        - asset: asset/font/SF-Pro-Display-Heavy.otf
        - asset: asset/font/SF-Pro-Display-Regular.otf
        - asset: asset/font/SF-Pro-Display-Semibold.otf
    - family: SF-Pro-Text
      fonts:
        - asset: asset/font/SF-Pro-Text-Bold.otf
        - asset: asset/font/SF-Pro-Text-Medium.otf
        - asset: asset/font/SF-Pro-Text-Regular.otf
        - asset: asset/font/SF-Pro-Text-Semibold.otf
