name: application_musicale
description: Application musicale

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.0.1
  flutter_svg: ^1.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
  - asset/image/
  - asset/icones/
  fonts:
    - family:  AppIcons
      fonts:
        - asset: asset/font/AppIcons.ttf
    - family: SFProDisplay
      fonts:
        - asset: asset/font/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: asset/font/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: asset/font/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: asset/font/SF-Pro-Display-Regular.otf
          weight: 400
    - family: SFProText
      fonts:
        - asset: asset/font/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: asset/font/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: asset/font/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: asset/font/SF-Pro-Text-Regular.otf
          weight: 400

